SELECT DISTINCT(T1.CART_ID) FROM
(SELECT CART_ID 
FROM CART_PRODUCTS
WHERE NAME = 'MILK') T1
JOIN
(SELECT CART_ID 
FROM CART_PRODUCTS
WHERE NAME = 'YOGURT') T2 ON T1.CART_ID = T2.CART_ID
ORDER BY T1.CART_ID
